version: "3.7"

services:
  database:
    image: postgres:latest
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"

  recommendationservice:
    image: ci/crypto-invest:1.0.0
    depends_on:
      database:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${PRICES_FOLDER}:/prices
    networks:
      - backend

networks:
  backend:
    driver: bridge
